eureka:
    client:
        serviceUrl:
            defaultZone: http://127.0.0.1:8888/eureka/
server:
    port: 1111
spring:
    application:
        name: cloud-config-server
    cloud:
        config:
            label: master
            server:
                git:
                    uri: https://github.com/gdh7732/cloud-vue-parent.git
                    search-paths: repo
    profiles:
        active: native
